site_name: pysrf
site_description: Symmetric Representation Factorization for matrix completion and rank estimation
site_author: Florian Mahner
site_url: https://florianmahner.github.io/pysrf/
repo_url: https://github.com/florianmahner/pysrf
repo_name: florianmahner/pysrf

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            filters: ["!^_"]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference:
    - Model (SRF): api/model.md
    - Cross-Validation: api/cross_validation.md
    - Sampling Bounds: api/bounds.md
    - Utilities: api/utils.md
  - Development: development.md

